build:
  commands:
    - composer install --no-dev --optimize-autoloader
    - npm ci
    - npm run build

deploy:
  commands:
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan event:cache

workers:
  - name: queue
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600 --queue=default

scheduler:
  command: php artisan schedule:run
