<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\CommunicationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\InvitationController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SsoController;
use App\Http\Controllers\SyncController;
use Illuminate\Support\Facades\Route;

// Guest-only auth routes
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login']);
});

Route::post('/logout', [AuthController::class, 'logout'])->name('logout')->middleware('auth');

// Invitation acceptance (no auth — the invitee doesn't have an account yet)
Route::get('/invitations/{token}/accept', [InvitationController::class, 'show'])->name('invitations.show');
Route::post('/invitations/{token}/accept', [InvitationController::class, 'accept'])->name('invitations.accept');

// SSO login via signed URL (generated by /api/sso/token)
Route::get('/auth/sso', [SsoController::class, 'login'])->name('sso.login');

// Authenticated app routes
Route::middleware('auth')->group(function () {
    Route::get('/', fn () => redirect('/dashboard'));

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/clients', [ClientController::class, 'index'])->name('clients.index');
    Route::get('/clients/{client}', [ClientController::class, 'show'])->name('clients.show');
    Route::post('/clients/{client}/analyse', [ClientController::class, 'analyse'])->name('clients.analyse');
    Route::post('/clients/{client}/mark-as-lost', [ClientController::class, 'markAsLost'])->name('clients.mark-as-lost');
    Route::post('/clients/{client}/restore', [ClientController::class, 'restore'])->name('clients.restore');

    Route::get('/communications', [CommunicationController::class, 'index'])->name('communications.index');
    Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index');

    Route::post('/sync', [SyncController::class, 'trigger'])->name('sync.trigger');

    // Admin-only routes
    Route::middleware('admin')->group(function () {
        Route::get('/settings', [SettingsController::class, 'index'])->name('settings.index');
        Route::delete('/settings/users/{user}', [SettingsController::class, 'removeUser'])->name('settings.users.remove');

        Route::post('/invitations', [InvitationController::class, 'store'])->name('invitations.store');
        Route::delete('/invitations/{invitation}', [InvitationController::class, 'destroy'])->name('invitations.destroy');
    });
});
